### GENERAL SETTINGS ###

# Site settings
title: WAO! 2016 
description: "We Are Open Festival 2016 - Il festival della creatività e dell'innovazione dal basso "
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://waofestival.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: http://facebook.com/fablabtoscana
  - title: twitter
    url: http://twitter.com/fablabtoscana
  - title: instagram
    url: https://www.instagram.com/fablabtoscana/
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Fab Lab Toscana
    - Via Mario Giuntini 192
    - Polo Tecnologico di Navacchio
    - Cascina (PI)
email: info@fablabtoscana.it
website: http://www.fablabtoscana.it

### GENERAL DATA FOR VARIOUS LOCATIONS ###


events:
    - name: 4 Giugno 2016
      items:
        - title: Apertura evento
          time: ore 10:00
          where: Palco
        - title: Workshop per le scuole a rotazione ogni 60 minuti
          time: ore 10:30 - 13:00
          where: Zona Workshop
        - title: Light talk, popup makers
          time: ore 14:30 - 16:00
          where: Zona Workshop
        - title: Workshop professionali
          time: ore 16:00 - 18:00
          where: Zona Workshop
        - title: Attività negli stand
          time: ore 10:00 - 19:00
          where: Area Espositiva
        - title: Live Music - Urbanika in concerto
          time: ore 19:00 - 23:00
          where: Palco
    - name: 5 Giugno 2016
      items:
        - title: Workshop per le scuole a rotazione ogni 60 minuti
          time: ore 10:30 - 13:00
          where: Zona Workshop
        - title: Light talk, popup makers
          time: ore 14:30 - 16:00
          where: Zona Workshop
        - title: Attività negli stand
          time: ore 10:00 - 19:00
          where: Area Espositiva
        - title: Wrap up
          time: ore 18:30 - 19:00
          where: Palco
        - title: Chiusura evento
          time: ore 19:00
          where: Palco
          

organizer:
    bio: Fab Lab Toscana è un laboratorio distribuito per la fabbricazione digitale. Nei nodi di Firenze, Siena, Cascina e Contea è possibile imparare e usare tutte le tecniche di fabbricazione con macchinari all'avanguardia e personale altamente qualificato. Il laboratorio fornisce il programma di formazione internazionale Fab Academy, organizza workshop ed eventi aperti al pubblico e collabora con Istituzioni, Scuole e Università per rendere la fabbricazione digitale accessibile a tutto il territorio toscano.
    url: http://www.fablabtoscana.it

    
# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients: 
    - name: Trotec
      img: trotec.jpg
      website: http://www.troteclaser.com/it-IT/Pages/Laser_systems.aspx
    - name: Roland DG
      img: roland.jpg
      website: http://www.rolanddg.it/it
    - name: KUKA
      img: kuka.png
      website: http://www.kuka-robotics.com/italy/it/
    - name: CampuStore
      img: campustore.png
      website: http://www.campustore.it/
    - name: ADS Group
      img: ads.png
      website: https://www.assembly.it/
    - name: UDOO
      img: udoo.png
      website: http://www.udoo.org/


partners:
  - name: Polo Tecnologico
    img: polo.png
    desc:
    website: http://www.polotecnologico.it
  - name: Università di Siena
    img: unisi.jpg
    website: http://santachiaralab.unisi.it
  - name: EU Maker Week
    img: lg_mw.png
    website: http://europeanmakerweek.eu
  - name: Comune di Cascina
    img: comune.png
    website: http://www.comune.cascina.pi.it/
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "WAO! 2016 E' il primo festival in Toscana a celebrare l'inventiva e la creatività dei makers a servizio di scuole, aziende e istituzioni"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO